# Generated by Django 4.1.7 on 2023-02-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Enter text please', max_length=1000),
        ),
    ]
